import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box, Text } from "@chakra-ui/react"
import Link from 'next/link'

export default function Home({ Component, pageProps }) {
  console.log("apples")
  return (
    <Box className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Email Utilities
        </h1>

        <Text className={styles.description}>
          Tools for building emails in Pardot
        </Text>

        <div className={styles.grid}>
          <Link href="/customize-image">
            <div className={styles.card}>
              <h2>Customize an Image &rarr;</h2>
            </div>
          </Link>
          <a target="_blank" rel="noreferrer" href="https://airtable.com/appbAhYQGUWnljk35/pagDS1LiP72L77oSk?eezFR=recpGeV6ar5QxygNI">
            <div className={styles.card}>
              <h2>Create a CTA Button ↗</h2>
            </div>
          </a>
          <a target="_blank" rel="noreferrer" href="https://ical.marudot.com/">
            <div className={styles.card}>
              <h2>Create a calendar file ↗</h2>
            </div>
          </a>
        </div>
      </main>
    </Box>
  )
}
